### PR TITLE
Update PKGBUILD to better suits the Arch Linux Packaging Guideline

### PR DESCRIPTION
**Pull request by Antiz96**
Hi,

First of all, congratulations for your awesome work with amethyst (and Crystal Linux in general).

I wanted to suggest some changes to the `amethyst`'s PKGBUILD to better suits the Arch Linux Packaging Guideline (hence this PR):

- The `pkgname` should be equal to the [AUR package](https://aur.archlinux.org/packages/ame) name (`ame`).
*This have apparently been corrected on the AUR's PKGBUILD  but not on this repo.*

- In my opinion, the `find` command used in the `package()` function makes it unnecessarily complex. An easier and more standard method would just be to `install` the `ame` binary like so:
`install -Dm 755 "target/release/$pkgname" "$pkgdir/usr/bin/$pkgname"`
I also think it makes the PKGBUILD clearer, so it is easier for the end user to understand what's being installed on their machine (which is always cool :smile:).

- While not being mandatory (as far as I know), best practices imply to copy the documentation in `/usr/share/doc/"package_name"`.
For `amethyst`, that means copying the `README.md` and the `docs/CONFIG.md` files to `/usr/share/doc/ame` in the `package()` function like so:
```
install -Dm 644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
install -Dm 644 docs/CONFIG.md "$pkgdir/usr/share/doc/$pkgname/CONFIG.md"
```

- The current PKGBUILD relies on a clone of the GitHub repo. While this is not an issue technically speaking, it makes checking the integrity of the downloaded resources pretty complex and hard to maintain, which apparently resulted in `sha256sums=('SKIP')` in the current PKGBUILD apparently :smile:.
An easy (and more standard) way to check the integrity of the download ressources would be to rely on the release's archive instead of a repo clone so you only need to check the archive integrity itself to validate the whole downloaded resources:
```
source=("$_pkgname-$pkgver-$pkgrel::$url/archive/v$pkgver.tar.gz")
sha256sums=('ae1e6336177b6fa64536c9a8876ba0bac510ac528153133b67cf3f5046b43583')
```
Obviously the hash of the archive will need to be updated at each releases accordingly.
Checking the integrity of the downloaded resources may not be mandatory but still recommended and makes the PKGBUILD way more trustworthy in my opinion.

This PR aims to improve the PKGBUILD according to the three points listed above (by a new `pkgrel`).

I remain available if needed :)

Once again, thanks for your awesome work!

Signed-off-by: Robin Candau <53110319+Antiz96@users.noreply.github.com>

### CODE REVIEW

**Comment by not-my-segfault** [comment]
This is fantastic, @SomethingGeneric should we potentially incorporate more of these changes into our other PKGBUILDs where appropriate?

**Review by fries1234 — COMMENTED** [review]
we should make this conflict with the existing amethyst package and change base to point to the this packages new name

**Comment by fries1234** [comment]
image
actually looks like makepkg has the perfect thing for this

**Comment by Antiz96** [comment]
> we should make this conflict with the existing amethyst package and change base to point to the this packages new name

Hi, what are you referencing as "the existing amethyst package" ?

**Comment by SomethingGeneric** [comment]
> This is fantastic, @SomethingGeneric should we potentially incorporate more of these changes into our other PKGBUILDs where appropriate?

Yeah as I recall we were already moving to not do pure git sources, right. 

> While not being mandatory (as far as I know), best practices imply to copy the documentation in `/usr/share/doc/"package_name"`.

Absolutely agree. That command is hideous. 

> Obviously the hash of the archive will need to be updated at each releases accordinly.

Arch has a lovely script, `updpkgsums`, which does this automatically. This is all awesome, tysm!

**Comment by fries1234** [comment]
> > we should make this conflict with the existing amethyst package and change base to point to the this packages new name
> 
> Hi, what are you referencing as "the existing amethyst package" ?

image
Crystal has a base package that pulls in a package called "amethyst"

**Review by not-my-segfault — APPROVED** [review]

**Comment by fries1234** [comment]
So if you want to rename it to "ame" you should make the pkgbuild conflict with the name "amethyst"

**Comment by SomethingGeneric** [comment]
@not-my-segfault we obviously will need to update the base package and jade once we merge this, and then clean out `amethyst` artifacts on the repo

**Comment by SomethingGeneric** [comment]
Not sure what the best order is, here.

**Comment by Antiz96** [comment]
> We should add a `replaces=()` directive so the correct package is swapped out for the user

Doing it RN

**Comment by Antiz96** [comment]
Update done.

Building test ok:
`:: ame et amethyst sont en conflit. Supprimer amethyst ? [o/N]'
(That means "ame and amethyst are in conflict, delete amethyst ? [y/N]" in french :smile:)

**Review by SomethingGeneric — APPROVED** [review]
LGTM. @not-my-segfault ?

**Review by fries1234 — APPROVED** [review]

**Review by not-my-segfault — APPROVED** [review]

**Comment by Antiz96** [comment]
Glad it helped :)

BTW, I kinda like maintaining packages and I'm often looking for new packages to submit/maintain on the AUR, so if you guys seek help with packaging/maintaining I'd be glad to help :)

**Comment by SomethingGeneric** [comment]
*Please* feel free to look over all of our `pkgbuild.XYZ` repos :relieved:

**Comment by Antiz96** [comment]
> _Please_ feel free to look over all of our `pkgbuild.XYZ` repos relieved

Will do !

**Comment by not-my-segfault** [comment]
> Glad it helped smile
> 
> BTW, I kinda like maintaining packages and I'm often looking for new packages to submit/maintain on the AUR, so if you guys seek help with packaging/maintaining I'd be glad to help :)

We're always looking for help in some of our most important teams (e.g., Packaging & QA), so if you'd be interested in getting more involved in that sense feel free to come talk to us in the [Discord](2b47CAKNAx), the [Matrix](https://matrix.to/#/#crystal:tar.black), or the [Forum](https://forum.getcryst.al) !

**Pull request merged**
